[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.x"
  NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
